services:
  - type: web
    name: ceraai-erp-setup-copilot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DEMO_USER
        value: demo
      - key: DEMO_PASS
        value: demo
